### ISSUE TITLE
post-build.sh fails "File exists" when re-building root

### ISSUE THREAD

**Issue by ryandrake08** [SunnyGuo-MYiR/myir-buildroot#1]
Re-building results in:

<pre>
>>>   Executing post-build script board/myir/myd_c335x/post-build.sh
ln: failed to create symbolic link '/home/user/src/myir-buildroot/output/target/lib/firmware/am335x-pru0-fw': File exists
Makefile:651: recipe for target 'target-finalize' failed
make[1]: *** [target-finalize] Error 1
Makefile:79: recipe for target '_all' failed
make: *** [_all] Error 2
</pre>

Patch to fix:

<pre>
diff --git a/board/myir/myd_c335x/post-build.sh b/board/myir/myd_c335x/post-build.sh
index 4a79dbd..9f1a0fa 100755
--- a/board/myir/myd_c335x/post-build.sh
+++ b/board/myir/myd_c335x/post-build.sh
@@ -1,6 +1,6 @@
 #!/bin/sh -e
 
 if [ -e ${TARGET_DIR}/lib/firmware/pru/PRU_Halt.out ]; then
-       ln -s /lib/firmware/pru/PRU_Halt.out ${TARGET_DIR}/lib/firmware/am335x-pru0-fw
-       ln -s /lib/firmware/pru/PRU_Halt.out ${TARGET_DIR}/lib/firmware/am335x-pru1-fw
+       ln -sf /lib/firmware/pru/PRU_Halt.out ${TARGET_DIR}/lib/firmware/am335x-pru0-fw
+       ln -sf /lib/firmware/pru/PRU_Halt.out ${TARGET_DIR}/lib/firmware/am335x-pru1-fw
 fi
</pre>

**Comment by SunnyGuo-MYiR** [comment]
Thank you!
